name: scipy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pip=25.1.1
  - jupyterlab=4.4.4
  - pip:
      - black==25.1.0
      - coloredlogs==15.0.1
      - matplotlib==3.10.3
      - mpld3==0.5.10
      - notebook==7.4.4
      - numpy==2.3.1
      - pandas==2.3.0
      - prettytable==3.16.0
      - prophet==1.1.7
      - pydub==0.25.1
      - ruff==0.12.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scipy==1.16.0
      - seaborn==0.13.2
      - sqlalchemy==2.0.41
      - streamlit==1.46.1
      - sympy==1.14.0
      - tqdm==4.67.1
      - typeguard==4.4.4
