name: scipy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.3
  - pip=25.1.1
  - pip:
      - black==25.1.0
      - matplotlib==3.10.1
      - numpy==2.2.5
      - ruff==0.11.8
      - seaborn==0.13.2
      - tqdm==4.67.1
      - typeguard==4.4.2
